### ISSUE TITLE
Integration into event loops

### ISSUE THREAD

**Issue by paddor** [paddor/rbnng#1]
This is an exciting gem. Thank you. I wonder if it's possible to integrate it into event loops like Async or EventMachine. For the latter, I think the `NNG_OPT_RECVFD` has to be read out first.

Any advice?

**Comment by adibsaad** [comment]
@paddor I don't have much experience with Async in Ruby, and I haven't used this gem in a while, but feedback is welcome :)

**Comment by paddor** [comment]
Using #2 it works pretty well.


Kinda like this:

```ruby
Async do
  sock = NNG::Socket::Rep0.new
  sock.listen(ADDR)
  loop do
    msg = sock.get_msg
    ...
  end
end
```

**Comment by paddor** [comment]
I know more now. All that's needed to make it work with Async (or EventMachine) is that `NNG_OPT_RECVFD` or `NNG_OPT_SENDFD`, respectively. I'll send a PR just for those.
